// This file will be generated by openapi-typescript
// Run: npm run generate
// For now, we'll define basic types manually

export type UserRole = 'admin' | 'user' | 'service';

export interface UserCreate {
  username: string;
  email: string;
  password: string;
}

export interface UserLogin {
  username: string;
  password: string;
}

export interface Token {
  access_token: string;
  refresh_token: string;
  token_type?: string;
}

export interface UserResponse {
  [key: string]: unknown;
  id: number;
  username: string;
  email: string;
  role: UserRole;
  is_active: boolean;
  created_at: string;
}

export interface ProxyCreate {
  ip: string;
  port: number;
  protocol?: string;
  username?: string | null;
  password?: string | null;
}

export interface ProxyResponse {
  [key: string]: unknown;
  id: number;
  ip: string;
  port: number;
  username?: string | null;
  latency?: number | null;
  last_checked?: string | null;
  is_working: boolean;
  fail_count: number;
  last_used?: string | null;
  address: string;
  health_score?: number | null;
  protocol?: string | null;
}

export interface ProxyTestResult {
  proxy_id: number;
  success: boolean;
  latency?: number | null;
  status_code?: number | null;
  error?: string | null;
}

export interface HealthResponse {
  status: string;
  message: string;
}

export interface ProxyStatsResponse {
  total: number;
  working: number;
  dead: number;
  statistics: Record<string, number>;
}

export interface BlacklistCreate {
  pattern: string;
  description?: string | null;
}

export interface BlacklistResponse {
  [key: string]: unknown;
  id: number;
  pattern: string;
  description?: string | null;
  created_at: string;
  created_by: number;
}

export interface ActivityLogResponse {
  [key: string]: unknown;
  id: number;
  user_id: number;
  endpoint: string;
  method: string;
  timestamp: string;
  status_code: number;
  target_url?: string | null;
  ip_address?: string | null;
}

export interface ActivityLogCreate {
  user_id?: number | null;
  endpoint: string;
  method: string;
  status_code: number;
  target_url?: string | null;
  proxy_id?: number | null;
  timestamp?: number | null;
}

export interface HTTPValidationError {
  detail: ValidationError[];
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

// API Key types
export interface ApiKeyCreate {
  name: string;
  expires_at?: string | null;
}

export interface ApiKeyResponse {
  id: number;
  prefix: string;
  name: string;
  created_at: string;
  expires_at?: string | null;
  is_active: boolean;
}

export interface ApiKeyCreateResponse {
  api_key: ApiKeyResponse;
  raw_key: string;
}

